{% set name = "apache-airflow-providers-apache-cassandra" %}
{% set version = "3.8.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_apache_cassandra-{{ version }}.tar.gz
  sha256: a9fdb69889ce66799201a400ba1c0d299d9c70a123f6efbb9e59590a3a9e7619

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - python >={{ python_min }}
    - apache-airflow >=2.10.0
    - cassandra-driver >=3.29.1

test:
  imports:
    - airflow.providers.apache.cassandra
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-apache-cassandra for Apache Airflow
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-apache-cassandra/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
