{% set name = "apache-airflow-providers-apache-cassandra" %}
{% set version = "3.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_apache_cassandra-{{ version }}.tar.gz
  sha256: 159b1fcd5752df33fd065bfa37ffc38325ca0fb936aca280048a62f09a71f8bc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - apache-airflow >=2.7.0
    - cassandra-driver >=3.29.1

test:
  imports:
    - airflow.providers.apache.cassandra
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-apache-cassandra for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/apache/cassandra/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-apache-cassandra/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
