{% set name = "apache-airflow-providers-apache-cassandra" %}
{% set version = "3.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-apache-cassandra-{{ version }}.tar.gz
  sha256: 6c472dc4b8c7a74fe06d49c375e31956288976808d7eb25f42927aab1148c2ab

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - apache-airflow >=2.3.0
    - cassandra-driver >=3.13.0

test:
  imports:
    - airflow.providers.apache.cassandra
    - airflow.providers.apache.cassandra.hooks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Airflow. Implements apache-airflow-providers-apache-cassandra package
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-apache-cassandra/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
