{% set name = "apache-airflow-providers-apache-cassandra" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-apache-cassandra-{{ version }}.tar.gz
  sha256: 44dc235b6ca375ab59496ba9b602e19413dfd89ed96f8167d6baef83907f43c6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - wheel
  run:
    - apache-airflow >=2.0.0
    - cassandra-driver >=3.13.0,<3.21.0
    - python >=3.6

test:
  imports:
    - airflow.providers.apache.cassandra
    - airflow.providers.apache.cassandra.example_dags
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Cassandra for Apache Airflow
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-apache-cassandra/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
